-- MySQL Script generated by MySQL Workbench
-- Fri May 13 11:10:24 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vneedu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vneedu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vneedu` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `vneedu` ;

-- -----------------------------------------------------
-- Table `vneedu`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`user` (
  `id` VARCHAR(45) NOT NULL,
  `at_id` VARCHAR(45) NULL COMMENT '用户唯一ID',
  `name` VARCHAR(45) NULL COMMENT '用户昵称（可选）',
  `phone` VARCHAR(16) NOT NULL COMMENT '用户手机号',
  `email` VARCHAR(128) NULL COMMENT '用户邮箱（可选）',
  `password_hash` VARCHAR(80) NOT NULL COMMENT 'BCrypt密码',
  `score` INT NULL COMMENT '用户积分（可选）',
  `level` INT NULL COMMENT '等级（可选）',
  `profile` VARCHAR(256) NULL COMMENT '用户简介（可选）',
  `avatar` VARCHAR(256) NULL COMMENT '用户头像URL（可选）',
  `area` VARCHAR(45) NULL COMMENT '用户所在地区（可选）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `at_id_UNIQUE` (`at_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`user_estimate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`user_estimate` (
  `id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL COMMENT '用户ID',
  `nice` INT NULL DEFAULT 0 COMMENT '用户被赞数（可选）',
  `commented` INT NULL DEFAULT 0 COMMENT '用户被评价数（可选）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`requirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`requirement` (
  `id` VARCHAR(45) NOT NULL,
  `title` VARCHAR(128) NOT NULL COMMENT '需求标题',
  `description` LONGTEXT NULL COMMENT '需求描述（可选）',
  `publisher_id` VARCHAR(45) NOT NULL COMMENT '发布者',
  `datetime` DATETIME NOT NULL COMMENT '发布日期',
  `image` VARCHAR(256) NULL COMMENT '需求主图，图片URL路径（可选）',
  `address` VARCHAR(128) NOT NULL COMMENT '需求地址',
  `price` INT NOT NULL COMMENT '需求价格',
  `pay_method` INT NOT NULL COMMENT '支付方式',
  `nice` INT NULL DEFAULT 0 COMMENT '赞（可选）',
  `trade_status` INT NULL DEFAULT 0 COMMENT '交易状态（可选）',
  `category_id` VARCHAR(45) NOT NULL COMMENT '分类ID',
  `removed` INT NULL DEFAULT 0 COMMENT '是否删除（可选）',
  `area` VARCHAR(45) NOT NULL COMMENT '需求地区',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`keyword` (
  `id` VARCHAR(45) NOT NULL,
  `keyword` VARCHAR(45) NOT NULL COMMENT '关键字',
  `requirement_id` VARCHAR(45) NOT NULL COMMENT '关联需求',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`category` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '分类名称',
  `icon` VARCHAR(256) NOT NULL COMMENT '分类图标',
  `type` VARCHAR(45) NOT NULL COMMENT '分类字段名',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`discussion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`discussion` (
  `id` VARCHAR(45) NOT NULL,
  `content` VARCHAR(256) NOT NULL COMMENT '讨论内容',
  `sender_id` VARCHAR(45) NOT NULL COMMENT '发布者',
  `requirement_id` VARCHAR(45) NOT NULL COMMENT '需求ID',
  `datetime` DATETIME NOT NULL COMMENT '发布时间',
  `removed` INT NULL DEFAULT 0 COMMENT '是否删除（可选）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`notification` (
  `id` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL COMMENT '消息类型',
  `target_id` VARCHAR(45) NULL COMMENT '关联类型ID（可选）',
  `receiver_id` VARCHAR(45) NOT NULL COMMENT '接收者ID',
  `content` VARCHAR(256) NULL COMMENT '通知内容（可选）',
  `removed` INT NULL DEFAULT 0 COMMENT '是否删除（可选）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`judgement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`judgement` (
  `id` VARCHAR(45) NOT NULL,
  `content` VARCHAR(256) NOT NULL COMMENT '评价内容',
  `requirement_id` VARCHAR(45) NOT NULL COMMENT '需求ID',
  `judge_id` VARCHAR(45) NOT NULL COMMENT '评价人ID',
  `user_id` VARCHAR(45) NOT NULL COMMENT '被评价人ID',
  `datetime` DATETIME NOT NULL COMMENT '评价时间',
  `is_req_creator` INT NULL DEFAULT 0 COMMENT '是否需求发起者（可选）',
  `score` INT NULL DEFAULT 5 COMMENT '评分（可选）',
  `removed` INT NULL DEFAULT 0 COMMENT '是否删除（可选）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`order_item` (
  `id` VARCHAR(45) NOT NULL,
  `creator_id` VARCHAR(45) NOT NULL COMMENT '订单创建者ID',
  `user_id` VARCHAR(45) NOT NULL COMMENT '需求发起者ID',
  `requirement_id` VARCHAR(45) NOT NULL COMMENT '需求ID',
  `order_no` VARCHAR(60) NOT NULL COMMENT '订单号',
  `status` INT NULL DEFAULT 0 COMMENT '订单状态（可选）',
  `datetime` DATETIME NOT NULL COMMENT '订单创建时间',
  `title` VARCHAR(128) NOT NULL COMMENT '需求标题',
  `image` VARCHAR(256) NULL COMMENT '需求主图URL（可选）',
  `price` VARCHAR(45) NOT NULL COMMENT '需求价格',
  `u_judged` INT NULL DEFAULT 0 COMMENT '需求发起者是否已经评价（可选）',
  `c_judged` INT NULL DEFAULT 0 COMMENT '订单创建者是否已经评价（可选）',
  `u_removed` INT NULL DEFAULT 0 COMMENT '需求发起者是否删除（可选）',
  `c_removed` INT NULL DEFAULT 0 COMMENT '订单创建者是否删除（可选）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`file` (
  `id` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(64) NOT NULL COMMENT '文件HASH',
  `location` VARCHAR(256) NOT NULL COMMENT '文件存储位置',
  `filename` VARCHAR(128) NOT NULL COMMENT '文件名称',
  `mime` VARCHAR(64) NOT NULL COMMENT '文件MIME',
  `size` INT(11) NOT NULL COMMENT '文件大小',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`user_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`user_file` (
  `id` VARCHAR(45) NOT NULL,
  `file_id` VARCHAR(45) NOT NULL COMMENT '文件ID',
  `display_name` VARCHAR(128) NOT NULL COMMENT '显示名',
  `uploader_id` VARCHAR(45) NOT NULL COMMENT '上传者',
  `url` VARCHAR(256) NOT NULL COMMENT '文件URL',
  `hash` VARCHAR(64) NOT NULL COMMENT '文件HASH',
  `datetime` DATETIME NOT NULL COMMENT '上传时间',
  `trashed` INT NULL DEFAULT 0 COMMENT '是否在回收站（可选）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vneedu`.`requirement_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vneedu`.`requirement_file` (
  `id` VARCHAR(45) NOT NULL,
  `user_file_id` VARCHAR(45) NOT NULL COMMENT '用户文件ID',
  `mime` VARCHAR(64) NOT NULL COMMENT '文件MIME',
  `requirement_id` VARCHAR(45) NOT NULL COMMENT '需求ID',
  `url` VARCHAR(256) NOT NULL COMMENT '文件URL',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
